# Generated by Django 5.2.17 on 2026-09-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_leaverequest_leaverequest_dates_idx_and_more'),
        ('leave', '0011_historical_availableleave_last_accrual'),
    ]

    operations = [
    ]
