# Generated by Django 5.2.17 on 2026-09-30 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0012_merge_upgrade_2_1_8'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Column already created by raw SQL in an earlier fork migration;
        # this only records it in Django's migration state.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='historicalavailableleave',
                    name='last_accrual_date',
                    field=models.DateField(blank=True, null=True, verbose_name='Last Accrual Date'),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='leaveaccrualrule',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='monthly_accrual',
            field=models.BooleanField(default=False, help_text='Accrue leave monthly (annual days ÷ 12) with DOJ pro-rata. Annual days come from grade/position accrual rules when set.', verbose_name='Monthly Accrual'),
        ),
        migrations.AlterField(
            model_name='leavetypecondition',
            name='condition_type',
            field=models.CharField(choices=[('gender', 'Gender'), ('once_per_employment', 'Once Per Employment'), ('marital_status', 'Marital Status'), ('nationality', 'Nationality'), ('department', 'Department'), ('employment_type', 'Employment Type'), ('employment_status', 'Employment Status'), ('grade', 'Grade'), ('service_duration', 'Service Duration')], max_length=50, verbose_name='Condition Type'),
        ),
    ]
