# Generated by Django 5.2 on 2026-08-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebankdetails',
            name='esi_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ESI Number'),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PAN Number'),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='pf_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='PF Number'),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='uan_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='UAN Number'),
        ),
    ]
