# Generated by Django 5.2.17 on 2026-09-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_policy_specific_employees_policy_department_and_more'),
        ('employee', '0008_probation_fields'),
    ]

    operations = [
    ]
