# Generated by Django 5.2 on 2026-08-31 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_alter_allowance_amount_and_more'),
        ('payroll', '0021_reimbursement_condition_approval'),
    ]

    operations = [
    ]
