# Generated by Django 5.2.17 on 2026-09-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_encashmentgeneralsettings_department_and_more'),
        ('payroll', '0022_merge_20260831_1254'),
    ]

    operations = [
    ]
