# Generated by Django 5.2 on 2026-08-17 11:57
#
# Seleric: upstream 2.1.8 drops Project.members here, but our fork keeps the
# field (project access checks in project/models.py and project/views.py rely
# on it). Kept as a no-op under the upstream name so 0005/0006 still resolve.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_timesheet_options"),
    ]

    operations = []
