# Generated by Django 4.2.23 on 2026-03-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_dynamicemailconfiguration_company_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="registration_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Registration Number"
            ),
        ),
    ]
