# Generated by Django 5.2 on 2026-08-31 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_rotatingworktype_name'),
        ('base', '0014_multiple_approval_condition_fields'),
    ]

    operations = [
    ]
