# Generated by Django 5.2.17 on 2026-09-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_merge_20260831_1254'),
        ('base', '0016_seed_default_export_permission'),
    ]

    operations = [
    ]
