# Generated by Django 5.2.17 on 2026-10-06 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevices',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='biometricdevices',
            name='machine_type',
            field=models.CharField(choices=[('zk', 'ZKTeco / eSSL Biometric'), ('anviz', 'Anviz Biometric'), ('cosec', 'Matrix COSEC Biometric'), ('dahua', 'Dahua Biometric'), ('etimeoffice', 'e-Time Office'), ('realtime', 'Realtime Biometric (web push)')], max_length=18, null=True, verbose_name='Device Type'),
        ),
        migrations.CreateModel(
            name='RealtimePunchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32, verbose_name='Device User ID')),
                ('punch_time', models.DateTimeField(verbose_name='Punch Time')),
                ('io_mode', models.IntegerField(blank=True, null=True)),
                ('verify_mode', models.IntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, default='', max_length=200)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_punches', to='biometric.biometricdevices')),
            ],
            options={
                'verbose_name': 'Realtime Punch Log',
                'verbose_name_plural': 'Realtime Punch Logs',
                'indexes': [models.Index(fields=['processed', 'punch_time'], name='biometric_r_process_5da3ab_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'user_id', 'punch_time'), name='unique_realtime_punch')],
            },
        ),
    ]
