# Generated by Django 5.2.17 on 2026-10-06 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0002_biometricdevices_serial_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeDeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_code', models.CharField(max_length=40)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for device'), ('sent', 'Sent'), ('ok', 'Done'), ('error', 'Failed')], default='waiting', max_length=10)),
                ('return_code', models.CharField(blank=True, default='', max_length=40)),
                ('result', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_commands', to='biometric.biometricdevices')),
            ],
            options={
                'verbose_name': 'Realtime Device Command',
                'verbose_name_plural': 'Realtime Device Commands',
                'indexes': [models.Index(fields=['device_id', 'status'], name='biometric_r_device__2f6862_idx')],
            },
        ),
    ]
