# Generated by Django 5.2.17 on 2026-10-06 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0003_realtimedevicecommand'),
        ('employee', '0009_merge_upgrade_2_1_8'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimedevicecommand',
            name='binary',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BiometricFaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(max_length=32)),
                ('backup_number', models.IntegerField()),
                ('data', models.BinaryField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_face_data', to='employee.employee')),
                ('source_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biometric.biometricdevices')),
            ],
            options={
                'verbose_name': 'Biometric Face Data',
                'verbose_name_plural': 'Biometric Face Data',
                'constraints': [models.UniqueConstraint(fields=('device_user_id', 'backup_number'), name='unique_biometric_face_data')],
            },
        ),
    ]
