# Generated by Django 5.2.17 on 2026-10-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0004_biometric_face_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevices',
            name='last_contact',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
