# Generated by Django 5.2 on 2026-08-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_punch_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="missing_punch_out",
            field=models.BooleanField(
                default=False,
                help_text="Set when employee checked in but did not punch out by end of day.",
                verbose_name="Missing Punch Out",
            ),
        ),
        migrations.AddField(
            model_name="historicalattendance",
            name="missing_punch_out",
            field=models.BooleanField(
                default=False,
                help_text="Set when employee checked in but did not punch out by end of day.",
                verbose_name="Missing Punch Out",
            ),
        ),
    ]
