# Generated by Django 5.2.17 on 2026-09-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_attendance_date_idx_and_more'),
        ('attendance', '0013_attendance_overtime_condition_approval'),
    ]

    operations = [
    ]
