# Generated by Django 5.2.17 on 2026-09-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_merge_upgrade_2_1_8'),
    ]

    operations = [
        # Column already created by raw SQL in an earlier fork migration;
        # this only records it in Django's migration state.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='historicalattendance',
                    name='punch_location',
                    field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Punch location'),
                ),
            ],
            database_operations=[],
        ),
        # Column already created by raw SQL in an earlier fork migration;
        # this only records it in Django's migration state.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='historicalattendanceactivity',
                    name='punch_location',
                    field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Punch location'),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='request_type',
            field=models.CharField(choices=[('create_request', 'Create Request'), ('update_request', 'Update Request'), ('created_request', 'Created Request'), ('missing_punch', 'Missing Punch')], default='update_request', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='historicalattendance',
            name='request_type',
            field=models.CharField(choices=[('create_request', 'Create Request'), ('update_request', 'Update Request'), ('created_request', 'Created Request'), ('missing_punch', 'Missing Punch')], default='update_request', max_length=18, null=True),
        ),
    ]
