"""URL routes for Indian statutory payroll."""

from django.urls import path

from payroll.views import india_statutory_views as views

urlpatterns = [
    path(
        "india-statutory/settings/",
        views.india_statutory_settings,
        name="india-statutory-settings",
    ),
    path(
        "india-statutory/employee/<int:emp_id>/",
        views.employee_statutory_profile,
        name="employee-statutory-profile",
    ),
    path(
        "india-statutory/form16/<int:emp_id>/",
        views.form16_view,
        name="form16-view",
    ),
    path(
        "india-statutory/form16/",
        views.form16_list,
        name="form16-list",
    ),
    path(
        "india-statutory/challans/",
        views.challan_list,
        name="challan-list",
    ),
    path(
        "india-statutory/challans/export/",
        views.challan_export,
        name="challan-export",
    ),
    path(
        "india-statutory/registers/",
        views.statutory_register,
        name="statutory-register",
    ),
    path(
        "india-statutory/registers/export/",
        views.statutory_register_export,
        name="statutory-register-export",
    ),
    path(
        "india-statutory/form24q/",
        views.form24q_list,
        name="form24q-list",
    ),
    path(
        "india-statutory/form24q/export/",
        views.form24q_export,
        name="form24q-export",
    ),
    path(
        "india-statutory/traces/",
        views.traces_efiling,
        name="traces-efiling",
    ),
    path(
        "india-statutory/traces/24q/",
        views.traces_24q_download,
        name="traces-24q-download",
    ),
    path(
        "india-statutory/traces/challan/",
        views.oltas_challan_download,
        name="oltas-challan-download",
    ),
    path(
        "india-statutory/accounting-export/",
        views.accounting_export_list,
        name="accounting-export-list",
    ),
    path(
        "india-statutory/accounting-export/download/",
        views.accounting_export_download,
        name="accounting-export-download",
    ),
    path(
        "india-statutory/excel/",
        views.statutory_excel_hub,
        name="statutory-excel-hub",
    ),
    path(
        "india-statutory/excel/template/",
        views.statutory_profiles_template,
        name="statutory-profiles-template",
    ),
    path(
        "india-statutory/excel/export/",
        views.statutory_profiles_export,
        name="statutory-profiles-export",
    ),
    path(
        "india-statutory/excel/import/",
        views.statutory_profiles_import,
        name="statutory-profiles-import",
    ),
    path(
        "india-statutory/form16/export/",
        views.form16_excel_export,
        name="form16-excel-export",
    ),
    path(
        "india-statutory/excel/ctc/template/",
        views.ctc_template,
        name="ctc-structure-template",
    ),
    path(
        "india-statutory/excel/ctc/export/",
        views.ctc_export,
        name="ctc-structure-export",
    ),
    path(
        "india-statutory/excel/ctc/import/",
        views.ctc_import,
        name="ctc-structure-import",
    ),
    path(
        "india-statutory/form16/import/template/",
        views.form16_import_template,
        name="form16-import-template",
    ),
    path(
        "india-statutory/form16/import/",
        views.form16_bulk_import,
        name="form16-bulk-import",
    ),
    path(
        "india-statutory/fnf/export/",
        views.fnf_excel_export,
        name="fnf-excel-export",
    ),
]
